// Inbound Session cases at paseo 53ee9cd9930d9479af318c1ed29713a0bfb5f47b.
// Source file: packages/server/src/server/session.ts (switch lines 2300-3200).
// gate is managed-only when Session calls authorizeCoworkWrite for that case.
// Unregistered agents still take the stock path. Every other case stays not-wired.

export type IngressLane = "session" | "subscribe" | "voice" | "hub";
export type IngressEffect = "read" | "write";
export type GateStatus = "not-wired" | "managed-only";

export interface SessionIngress {
  type: string;
  lane: IngressLane;
  effect: IngressEffect;
  gate: GateStatus;
}

export const SESSION_INGRESS: readonly SessionIngress[] = [
  { type: "agent.skills.get_status.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "agent.skills.reconcile.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "agent.skills.uninstall.request", lane: "session", effect: "write", gate: "not-wired" },
  {
    type: "agent.skills.save_selection.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  {
    type: "agent.skills.import_legacy_selection.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  { type: "voice_audio_chunk", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "abort_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "audio_played", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "set_voice_mode", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "dictation_stream_start", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "dictation_stream_chunk", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "dictation_stream_finish", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "dictation_stream_cancel", lane: "voice", effect: "read", gate: "not-wired" },
  { type: "restart_server_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "shutdown_server_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "client_heartbeat", lane: "session", effect: "read", gate: "not-wired" },
  { type: "ping", lane: "session", effect: "read", gate: "not-wired" },
  { type: "agent.rewind.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "agent.detach.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "fetch_agent_timeline_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "agent.timeline.append.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "agent.timeline.search.request", lane: "session", effect: "read", gate: "not-wired" },
  {
    type: "agent.timeline.list_prompts.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "agent.provider_subagents.list.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "agent.provider_subagents.timeline.get.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "session.events.set_subscription.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "agent.timeline.set_subscription.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "agent.fork_context.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "agent.create.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "creation.subscribe.request", lane: "subscribe", effect: "read", gate: "not-wired" },
  { type: "workspace.create.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "fetch_agents_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "fetch_agent_history_request", lane: "session", effect: "read", gate: "not-wired" },
  {
    type: "fetch_recent_provider_sessions_request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "fetch_agent_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "delete_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "archive_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "close_items_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "update_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "project.rename.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "project.icon.set.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "send_agent_message_request", lane: "session", effect: "write", gate: "managed-only" },
  { type: "wait_for_finish_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "create_agent_request", lane: "session", effect: "write", gate: "managed-only" },
  { type: "resume_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "import_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "refresh_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "cancel_agent_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "agent_permission_response", lane: "session", effect: "write", gate: "not-wired" },
  { type: "clear_agent_attention", lane: "session", effect: "write", gate: "not-wired" },
  { type: "set_agent_mode_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "set_agent_model_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "set_agent_feature_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "set_agent_thinking_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "agent.config.apply.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "get_daemon_config_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "daemon.get_status.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "daemon.get_pairing_offer.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "daemon.config.reload.request", lane: "session", effect: "write", gate: "not-wired" },
  {
    type: "hub.management.daemon.connect.request",
    lane: "hub",
    effect: "write",
    gate: "not-wired",
  },
  {
    type: "hub.management.daemon.get_status.request",
    lane: "hub",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "hub.management.daemon.disconnect.request",
    lane: "hub",
    effect: "write",
    gate: "not-wired",
  },
  {
    type: "hub.management.daemon.permissions.update.request",
    lane: "hub",
    effect: "write",
    gate: "not-wired",
  },
  { type: "diagnostics.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "daemon.update.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "set_daemon_config_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "read_project_config_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "write_project_config_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_status_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "checkout.commits.list.request", lane: "session", effect: "read", gate: "not-wired" },
  {
    type: "checkout.commits.file_diff.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "validate_branch_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "branch_suggestions_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "directory_suggestions_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "checkout.diff.get.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "subscribe_checkout_diff_request", lane: "subscribe", effect: "read", gate: "not-wired" },
  {
    type: "unsubscribe_checkout_diff_request",
    lane: "subscribe",
    effect: "read",
    gate: "not-wired",
  },
  { type: "checkout_switch_branch_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout.rename_branch.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_commit_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_merge_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_merge_from_base_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_pull_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_push_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout.refresh.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout.discard_changes.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_pr_create_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "checkout_pr_merge_request", lane: "session", effect: "write", gate: "not-wired" },
  {
    type: "checkout.forge.set_auto_merge.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  {
    type: "checkout.github.set_auto_merge.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  {
    type: "checkout.forge.get_check_details.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "checkout.github.get_check_details.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "checkout_pr_status_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "pull_request_timeline_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "forge.search.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "github_search_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "stash_save_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "stash_pop_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "stash_list_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "fetch_workspaces_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "project.list.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "paseo_worktree_list_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "paseo_worktree_archive_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "create_paseo_worktree_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "list_available_editors_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "open_in_editor_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "open_project_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "project.add.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "project.create_directory.request", lane: "session", effect: "write", gate: "not-wired" },
  {
    type: "workspace.github.search_repositories.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "project.github.clone.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "archive_workspace_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "project.remove.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "workspace.title.set.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "workspace.pin.set.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "workspace.label.list.request", lane: "session", effect: "read", gate: "not-wired" },
  {
    type: "workspace.label.assignment.set.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  { type: "workspace.label.update.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "workspace.label.delete.request", lane: "session", effect: "write", gate: "not-wired" },
  {
    type: "workspace.label.delete.inspect.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "file_explorer_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "fs.file.subscribe.request", lane: "subscribe", effect: "read", gate: "not-wired" },
  { type: "fs.file.unsubscribe.request", lane: "subscribe", effect: "read", gate: "not-wired" },
  { type: "fs.file.write.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "fs.entry.create.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "fs.entry.rename.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "fs.entry.duplicate.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "fs.entry.delete.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "project_icon_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "project.icon.get.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "file_download_token_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "file.upload.request", lane: "session", effect: "write", gate: "not-wired" },
  {
    type: "workspace.recovery.inspect.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  {
    type: "workspace.recovery.restore.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  {
    type: "workspace.clear_attention.request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  { type: "workspace.mark_unread.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "list_provider_models_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "list_provider_modes_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "list_provider_features_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "list_available_providers_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "get_providers_snapshot_request", lane: "session", effect: "read", gate: "not-wired" },
  {
    type: "refresh_providers_snapshot_request",
    lane: "session",
    effect: "write",
    gate: "not-wired",
  },
  { type: "provider_diagnostic_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "provider.usage.list.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "usage.list_reports.request", lane: "session", effect: "read", gate: "not-wired" },
  {
    type: "agent.resolve_usage_report.request",
    lane: "session",
    effect: "read",
    gate: "not-wired",
  },
  { type: "start_workspace_script_request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "workspace.script.list.request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "workspace.script.start.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "workspace.script.stop.request", lane: "session", effect: "write", gate: "not-wired" },
  { type: "schedule/create", lane: "session", effect: "write", gate: "not-wired" },
  { type: "schedule/list", lane: "session", effect: "read", gate: "not-wired" },
  { type: "schedule/inspect", lane: "session", effect: "read", gate: "not-wired" },
  { type: "schedule/logs", lane: "session", effect: "read", gate: "not-wired" },
  { type: "schedule/pause", lane: "session", effect: "write", gate: "not-wired" },
  { type: "schedule/resume", lane: "session", effect: "write", gate: "not-wired" },
  { type: "schedule/delete", lane: "session", effect: "write", gate: "not-wired" },
  { type: "schedule/run-once", lane: "session", effect: "write", gate: "not-wired" },
  { type: "schedule/update", lane: "session", effect: "write", gate: "not-wired" },
  { type: "list_commands_request", lane: "session", effect: "read", gate: "not-wired" },
  { type: "register_push_token", lane: "session", effect: "write", gate: "not-wired" },
  { type: "push.unregister.request", lane: "session", effect: "write", gate: "not-wired" },
];

export function ingressByType(type: string): SessionIngress | undefined {
  return SESSION_INGRESS.find((row) => row.type === type);
}

/** Stock Paseo sends are not cowork instructions unless that ingress is managed-only. */
export function assertIngressGated(type: string): void {
  const row = ingressByType(type);
  if (row?.gate === "managed-only") return;
  const label = row ? `${row.lane}/${row.effect}` : "unclassified";
  throw new Error(
    `CoworkMutationGate is not wired for ${type} (${label}). ` +
      "Refusing to treat a stock Paseo ingress as an authorized cowork command.",
  );
}
